source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'IFGMediaCapture_Example', :exclusive => true do
  pod 'IFGMediaCapture', :path => '../'
end

target 'IFGMediaCapture_Tests', :exclusive => true do
  pod 'IFGMediaCapture', :path => '../'

  
end
